-- =============================================================================
-- Formulario de contacto propio (no el de soporte). 2026-09-29
--
-- QA del 28/09: «Trabaja con nosotros» no hacia nada y «Contacto» llevaba al
-- formulario de soporte al cliente; deberia ser un formulario de contacto.
-- Cualquiera (con o sin cuenta) escribe desde «Sobre nosotros» (#contacto);
-- el admin lo lee en /admin/soporte, pestana «Contacto». Sin URL nueva.
--
-- - contact_messages: tipo (contacto, trabaja con nosotros, prensa,
--   colaboraciones), nombre, email, mensaje. Limites de longitud y formato.
-- - RLS: anon y authenticated solo INSERTAN (sin leer nada); el admin
--   (opynio_is_admin()) lee, marca y archiva.
-- - Anti-abuso: maximo 5 mensajes por email y hora (trigger) y el estado lo
--   pone el servidor ('new').
--
-- Idempotente. Rollback: DROP TABLE public.contact_messages CASCADE; DROP
-- FUNCTION public.contact_messages_guard().
-- =============================================================================

BEGIN;
SET LOCAL lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  kind text NOT NULL DEFAULT 'contact'
    CHECK (kind IN ('contact', 'careers', 'press', 'partnership')),
  name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 2 AND 100),
  email text NOT NULL CHECK (char_length(email) <= 200 AND email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  message text NOT NULL CHECK (char_length(btrim(message)) BETWEEN 10 AND 5000),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'archived')),
  admin_notes text
);

CREATE INDEX IF NOT EXISTS contact_messages_status_created_idx ON public.contact_messages (status, created_at DESC);
CREATE INDEX IF NOT EXISTS contact_messages_email_created_idx ON public.contact_messages (lower(email), created_at DESC);

-- El servidor fija estado, autor y fecha; limita la frecuencia por email.
CREATE OR REPLACE FUNCTION public.contact_messages_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.opynio_is_admin() THEN
    RETURN NEW;
  END IF;
  NEW.status := 'new';
  NEW.admin_notes := NULL;
  NEW.created_at := now();
  NEW.user_id := auth.uid();
  NEW.email := lower(btrim(NEW.email));
  NEW.name := btrim(NEW.name);
  IF (SELECT count(*) FROM public.contact_messages
       WHERE lower(email) = NEW.email AND created_at > now() - interval '1 hour') >= 5 THEN
    RAISE EXCEPTION 'contact_rate_limited' USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_contact_messages_guard ON public.contact_messages;
CREATE TRIGGER trg_contact_messages_guard
  BEFORE INSERT ON public.contact_messages
  FOR EACH ROW EXECUTE FUNCTION public.contact_messages_guard();

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can send a contact message" ON public.contact_messages;
CREATE POLICY "Anyone can send a contact message"
  ON public.contact_messages FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins manage contact messages" ON public.contact_messages;
CREATE POLICY "Admins manage contact messages"
  ON public.contact_messages FOR ALL TO authenticated
  USING (public.opynio_is_admin())
  WITH CHECK (public.opynio_is_admin());

REVOKE ALL ON public.contact_messages FROM anon, authenticated;
GRANT INSERT ON public.contact_messages TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON public.contact_messages TO authenticated;

COMMIT;
