-- =============================================================================
-- Solicitudes de soporte (tickets). 2026-09-25
--
-- Hasta ahora «Soporte» solo tenia formularios sueltos (error, reclamar empresa,
-- apelar resena) que mandaban un correo, y la tarjeta «Soporte» del panel de
-- admin estaba en «Proximamente». Esto crea el hilo de conversacion:
--
-- - support_tickets: una fila por solicitud. Tipo cerrado (question, account,
--   billing, business, account_deletion, other) y estado (open, in_progress,
--   waiting_user, resolved, closed).
-- - support_ticket_messages: los mensajes del hilo. `is_staff` lo pone el
--   servidor (trigger), nunca el cliente: true solo si escribe un admin en una
--   solicitud que no es suya.
--
-- Permisos (RLS):
-- - El usuario ve y crea solo lo suyo; responde en sus solicitudes no cerradas.
--   No puede tocar las filas de support_tickets con UPDATE: para cerrar o
--   reabrir la suya usa support_ticket_set_status(), que solo le deja esas dos
--   transiciones. Nadie borra por la API.
-- - El admin (opynio_is_admin(), como las migraciones del 23-24/09) ve todo,
--   responde y cambia cualquier estado (misma funcion).
-- - anon: nada.
--
-- Al responder un admin, un trigger inserta una notificacion en
-- public.notifications (la campana de la cabecera; solo user_id, type y
-- message, las columnas comunes a prod y local) y pasa la solicitud a
-- «waiting_user». Si responde el usuario, vuelve a «open».
--
-- Tambien anade public.notifications a la publicacion supabase_realtime si
-- existe y no estaba (AuthContext ya se suscribe a sus INSERT; con RLS, cada
-- usuario solo recibe los suyos). Si no hay publicacion o no hay permiso, se
-- avisa con NOTICE y se sigue: la notificacion aparece igual al recargar.
--
-- Sin adjuntos (fuera de esta version).
--
-- Vuelta atras:
--   DROP FUNCTION IF EXISTS public.admin_list_support_tickets(text, text, text, int, int);
--   DROP FUNCTION IF EXISTS public.admin_support_ticket_counts();
--   DROP FUNCTION IF EXISTS public.support_ticket_set_status(bigint, text);
--   DROP FUNCTION IF EXISTS public.create_support_ticket(text, text, text, uuid);
--   DROP TABLE IF EXISTS public.support_ticket_messages;
--   DROP TABLE IF EXISTS public.support_tickets;
--   DROP FUNCTION IF EXISTS public.support_tickets_before_write();
--   DROP FUNCTION IF EXISTS public.support_messages_before_insert();
--   DROP FUNCTION IF EXISTS public.support_messages_after_insert();
--   (la publicacion de notifications se puede dejar: no depende de esto)
-- =============================================================================
BEGIN;

-- ---------------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type            text NOT NULL DEFAULT 'question'
                  CHECK (type IN ('question', 'account', 'billing', 'business', 'account_deletion', 'other')),
  subject         text NOT NULL
                  CHECK (char_length(btrim(subject)) BETWEEN 3 AND 150),
  status          text NOT NULL DEFAULT 'open'
                  CHECK (status IN ('open', 'in_progress', 'waiting_user', 'resolved', 'closed')),
  business_id     uuid REFERENCES public.businesses(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.support_ticket_messages (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  bigint NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  author_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_staff   boolean NOT NULL DEFAULT false,
  body       text NOT NULL
             CHECK (char_length(btrim(body)) BETWEEN 1 AND 5000),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_user_last
  ON public.support_tickets (user_id, last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status_last
  ON public.support_tickets (status, last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_messages_ticket_created
  ON public.support_ticket_messages (ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_support_messages_author_created
  ON public.support_ticket_messages (author_id, created_at DESC);

ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_messages ENABLE ROW LEVEL SECURITY;

-- En prod `postgres` concede todo a anon/authenticated en public por defecto.
REVOKE ALL ON TABLE public.support_tickets FROM anon, authenticated, public;
REVOKE ALL ON TABLE public.support_ticket_messages FROM anon, authenticated, public;
GRANT SELECT, INSERT ON TABLE public.support_tickets TO authenticated;
GRANT SELECT, INSERT ON TABLE public.support_ticket_messages TO authenticated;
GRANT ALL ON TABLE public.support_tickets TO service_role;
GRANT ALL ON TABLE public.support_ticket_messages TO service_role;

-- ---------------------------------------------------------------------------
-- Politicas
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "support_tickets_select_own_or_admin" ON public.support_tickets;
CREATE POLICY "support_tickets_select_own_or_admin"
  ON public.support_tickets FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.opynio_is_admin());

DROP POLICY IF EXISTS "support_tickets_insert_own" ON public.support_tickets;
CREATE POLICY "support_tickets_insert_own"
  ON public.support_tickets FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "support_messages_select_own_or_admin" ON public.support_ticket_messages;
CREATE POLICY "support_messages_select_own_or_admin"
  ON public.support_ticket_messages FOR SELECT TO authenticated
  USING (
    public.opynio_is_admin()
    OR EXISTS (SELECT 1 FROM public.support_tickets t
               WHERE t.id = ticket_id AND t.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "support_messages_insert_own_or_admin" ON public.support_ticket_messages;
CREATE POLICY "support_messages_insert_own_or_admin"
  ON public.support_ticket_messages FOR INSERT TO authenticated
  WITH CHECK (
    author_id = auth.uid()
    AND (
      public.opynio_is_admin()
      OR EXISTS (SELECT 1 FROM public.support_tickets t
                 WHERE t.id = ticket_id AND t.user_id = auth.uid() AND t.status <> 'closed')
    )
  );

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Solicitudes: al crear, estado y fechas los pone el servidor, la empresa (si
-- la hay) tiene que ser del usuario y hay tope de 5 por hora (no admin). Al
-- actualizar (solo desde las funciones de abajo), user_id y created_at no se
-- mueven.
CREATE OR REPLACE FUNCTION public.support_tickets_before_write()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_recent int;
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.subject := btrim(NEW.subject);
    NEW.created_at := now();
    NEW.updated_at := now();
    NEW.last_message_at := now();
    IF auth.uid() IS NOT NULL AND NOT public.opynio_is_admin() THEN
      NEW.status := 'open';
      IF NEW.business_id IS NOT NULL
         AND NOT public.user_owns_business(NEW.business_id::text) THEN
        RAISE EXCEPTION 'support_ticket_business_not_owned' USING ERRCODE = '42501';
      END IF;
      SELECT count(*) INTO v_recent
      FROM public.support_tickets
      WHERE user_id = NEW.user_id AND created_at > now() - interval '1 hour';
      IF v_recent >= 5 THEN
        RAISE EXCEPTION 'support_ticket_rate_limited' USING ERRCODE = 'P0001';
      END IF;
    END IF;
  ELSE
    NEW.id := OLD.id;
    NEW.user_id := OLD.user_id;
    NEW.created_at := OLD.created_at;
    NEW.updated_at := now();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_support_tickets_before_write ON public.support_tickets;
CREATE TRIGGER trg_support_tickets_before_write
  BEFORE INSERT OR UPDATE ON public.support_tickets
  FOR EACH ROW EXECUTE FUNCTION public.support_tickets_before_write();

-- Mensajes: autor, fecha e is_staff los decide el servidor. Tope de 30
-- mensajes por hora para quien no es admin.
CREATE OR REPLACE FUNCTION public.support_messages_before_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_owner  uuid;
  v_recent int;
BEGIN
  SELECT user_id INTO v_owner FROM public.support_tickets WHERE id = NEW.ticket_id;
  NEW.body := btrim(NEW.body);
  NEW.created_at := now();
  IF auth.uid() IS NOT NULL THEN
    NEW.author_id := auth.uid();
    NEW.is_staff := public.opynio_is_admin() AND v_owner IS DISTINCT FROM auth.uid();
    IF NOT NEW.is_staff THEN
      SELECT count(*) INTO v_recent
      FROM public.support_ticket_messages
      WHERE author_id = auth.uid() AND created_at > now() - interval '1 hour';
      IF v_recent >= 30 THEN
        RAISE EXCEPTION 'support_message_rate_limited' USING ERRCODE = 'P0001';
      END IF;
    END IF;
  END IF;
  -- Sin sesion (service_role / SQL): se respeta lo que venga.
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_support_messages_before_insert ON public.support_ticket_messages;
CREATE TRIGGER trg_support_messages_before_insert
  BEFORE INSERT ON public.support_ticket_messages
  FOR EACH ROW EXECUTE FUNCTION public.support_messages_before_insert();

-- Tras un mensaje: fecha del ultimo mensaje y estado; si es de soporte, aviso
-- en la web al usuario. SECURITY DEFINER: el usuario no tiene UPDATE sobre la
-- solicitud ni INSERT sobre notificaciones ajenas.
CREATE OR REPLACE FUNCTION public.support_messages_after_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_ticket public.support_tickets%ROWTYPE;
BEGIN
  SELECT * INTO v_ticket FROM public.support_tickets WHERE id = NEW.ticket_id;
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  UPDATE public.support_tickets
     SET last_message_at = NEW.created_at,
         status = CASE
           WHEN NEW.is_staff AND status IN ('open', 'in_progress') THEN 'waiting_user'
           WHEN NOT NEW.is_staff AND status IN ('waiting_user', 'resolved') THEN 'open'
           ELSE status
         END
   WHERE id = NEW.ticket_id;

  IF NEW.is_staff THEN
    INSERT INTO public.notifications (user_id, type, message)
    VALUES (v_ticket.user_id, 'support_reply', left(v_ticket.subject, 150));
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_support_messages_after_insert ON public.support_ticket_messages;
CREATE TRIGGER trg_support_messages_after_insert
  AFTER INSERT ON public.support_ticket_messages
  FOR EACH ROW EXECUTE FUNCTION public.support_messages_after_insert();

-- ---------------------------------------------------------------------------
-- Funciones que usa el front
-- ---------------------------------------------------------------------------

-- Crea la solicitud y su primer mensaje de una vez (una solicitud sin mensaje
-- no sirve). SECURITY INVOKER: pasan las politicas y los triggers de arriba.
CREATE OR REPLACE FUNCTION public.create_support_ticket(
  p_type text,
  p_subject text,
  p_body text,
  p_business_id uuid DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '42501';
  END IF;
  INSERT INTO public.support_tickets (user_id, type, subject, business_id)
  VALUES (auth.uid(), COALESCE(NULLIF(btrim(p_type), ''), 'question'), p_subject, p_business_id)
  RETURNING id INTO v_id;
  INSERT INTO public.support_ticket_messages (ticket_id, author_id, body)
  VALUES (v_id, auth.uid(), p_body);
  RETURN v_id;
END;
$$;

-- Cambio de estado. Admin: cualquiera. Usuario, en la suya: cerrarla (desde
-- cualquier estado) o reabrirla (desde resolved/closed).
CREATE OR REPLACE FUNCTION public.support_ticket_set_status(p_ticket_id bigint, p_status text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_owner  uuid;
  v_status text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN ('open', 'in_progress', 'waiting_user', 'resolved', 'closed') THEN
    RAISE EXCEPTION 'support_ticket_bad_status' USING ERRCODE = '22023';
  END IF;

  SELECT user_id, status INTO v_owner, v_status
  FROM public.support_tickets WHERE id = p_ticket_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'support_ticket_not_found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT public.opynio_is_admin() THEN
    IF v_owner IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'support_ticket_not_found' USING ERRCODE = 'P0002';
    END IF;
    IF NOT (p_status = 'closed'
            OR (p_status = 'open' AND v_status IN ('resolved', 'closed'))) THEN
      RAISE EXCEPTION 'support_ticket_forbidden_status' USING ERRCODE = '42501';
    END IF;
  END IF;

  UPDATE public.support_tickets SET status = p_status WHERE id = p_ticket_id;
  RETURN p_status;
END;
$$;

-- Bandeja del admin: filtros, busqueda (asunto, n.º, nombre, usuario, email)
-- y paginacion, con nombre y email del usuario (auth.users solo desde aqui).
CREATE OR REPLACE FUNCTION public.admin_list_support_tickets(
  p_status text DEFAULT NULL,
  p_type text DEFAULT NULL,
  p_search text DEFAULT NULL,
  p_limit int DEFAULT 25,
  p_offset int DEFAULT 0
)
RETURNS TABLE (
  id bigint,
  user_id uuid,
  user_name text,
  user_username text,
  user_email text,
  type text,
  subject text,
  status text,
  business_id uuid,
  business_name text,
  created_at timestamptz,
  updated_at timestamptz,
  last_message_at timestamptz,
  message_count bigint,
  last_is_staff boolean,
  total_count bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_status text := NULLIF(NULLIF(btrim(p_status), ''), 'all');
  v_type   text := NULLIF(NULLIF(btrim(p_type), ''), 'all');
  v_search text := NULLIF(btrim(p_search), '');
  v_num    bigint;
BEGIN
  IF NOT public.opynio_is_admin() THEN
    RAISE EXCEPTION 'Acción solo para administradores.' USING ERRCODE = '42501';
  END IF;
  IF v_search ~ '^#?[0-9]{1,15}$' THEN
    v_num := ltrim(v_search, '#')::bigint;
  END IF;

  RETURN QUERY
  SELECT t.id, t.user_id, p.name, p.username, u.email::text,
         t.type, t.subject, t.status, t.business_id, b.name::text,
         t.created_at, t.updated_at, t.last_message_at,
         (SELECT count(*) FROM public.support_ticket_messages m WHERE m.ticket_id = t.id),
         (SELECT m.is_staff FROM public.support_ticket_messages m
           WHERE m.ticket_id = t.id ORDER BY m.created_at DESC, m.id DESC LIMIT 1),
         count(*) OVER ()
  FROM public.support_tickets t
  LEFT JOIN public.profiles p ON p.id = t.user_id
  LEFT JOIN auth.users u ON u.id = t.user_id
  LEFT JOIN public.businesses b ON b.id = t.business_id
  WHERE (v_status IS NULL
         OR (v_status = 'active' AND t.status IN ('open', 'in_progress', 'waiting_user'))
         OR t.status = v_status)
    AND (v_type IS NULL OR t.type = v_type)
    AND (v_search IS NULL
         OR t.id = v_num
         OR t.subject ILIKE '%' || v_search || '%'
         OR p.name ILIKE '%' || v_search || '%'
         OR p.username ILIKE '%' || v_search || '%'
         OR u.email ILIKE '%' || v_search || '%')
  ORDER BY (t.status = 'open') DESC, t.last_message_at DESC, t.id DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 25), 1), 100)
  OFFSET GREATEST(COALESCE(p_offset, 0), 0);
END;
$$;

-- Contadores por estado (pestañas del admin y tarjeta del panel).
CREATE OR REPLACE FUNCTION public.admin_support_ticket_counts()
RETURNS TABLE (status text, n bigint)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.opynio_is_admin() THEN
    RAISE EXCEPTION 'Acción solo para administradores.' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY SELECT t.status, count(*) FROM public.support_tickets t GROUP BY t.status;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.support_tickets_before_write() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.support_messages_before_insert() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.support_messages_after_insert() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.create_support_ticket(text, text, text, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.support_ticket_set_status(bigint, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_list_support_tickets(text, text, text, int, int) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_support_ticket_counts() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.create_support_ticket(text, text, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.support_ticket_set_status(bigint, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_support_tickets(text, text, text, int, int) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_support_ticket_counts() TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Realtime de la campana (ver cabecera)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (SELECT 1 FROM pg_publication_tables
                     WHERE pubname = 'supabase_realtime'
                       AND schemaname = 'public' AND tablename = 'notifications') THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
    EXCEPTION WHEN insufficient_privilege OR object_not_in_prerequisite_state THEN
      RAISE NOTICE 'notifications no se pudo anadir a supabase_realtime: %', SQLERRM;
    END;
  END IF;
END;
$$;

COMMIT;
